apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins-cicd-demo-web
  name: jenkins-cicd-demo-web
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: jenkins-cicd-demo-web
  type: LoadBalancer
